name: Bug report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run 'pkt create --language node'
        2. Run 'pkt add react'
        3. See error...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: |
        - OS: [e.g. Ubuntu 22.04, macOS 14, Windows 11]
        - PKT Version: [e.g. 1.0.0]
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please paste any relevant logs or output here.
